nome = str(input('Digite seu nome: ')).strip()
print(f'Seu nome em maiúsculo é: {(nome).upper()}')
print(f'Seu nome em minúsculo é:{(nome).lower()}')
print(f'Seu nome tem ao todo {len(nome) - nome.count(" ")}')
separa = nome.split()
print(f'Seu primeiro nome tem: {len(separa[0])}')
